name: Task App Development Action

on: 
  push:
    branches: [main]
    
  pull_request:
    branches: [main]

jobs:  
  build:
    name: flutter build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "11.0"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.0.1"
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test